github.com:
    user: imsakg
    git_protocol: https
    users:
        imsakg:
            oauth_token: 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
    oauth_token: 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
