terminal:
  colorScheme:
    name: Pro
    foreground: '#f2f2f2'
    background: '#000000'
    cursor: '#4d4d4d'
    colors:
      - '#000000'
      - '#990000'
      - '#00a600'
      - '#999900'
      - '#2009db'
      - '#b200b2'
      - '#00a6b2'
      - '#bfbfbf'
      - '#666666'
      - '#e50000'
      - '#00d900'
      - '#e5e500'
      - '#0000ff'
      - '#e500e5'
      - '#00e5e5'
      - '#e5e5e5'
  environment: {}
  fontSize: 17
  font: Cascadia Code
  bell: visual
  background: colorScheme
  customColorSchemes:
    - name: VibrantInk
      foreground: '#00ff00'
      background: '#000000'
      cursor: '#ffffff'
      colors:
        - '#878787'
        - '#ff6600'
        - '#ccff04'
        - '#ffcc00'
        - '#44b4cc'
        - '#9933cc'
        - '#44b4cc'
        - '#f5f5f5'
        - '#555555'
        - '#ff0000'
        - '#045a7d'
        - '#ffff00'
        - '#0000ff'
        - '#ff00ff'
        - '#009100'
        - '#e5e5e5'
  wordSeparator: ' ()[]{}''"'''''
  searchOptions: {}
  frontend: xterm
  hideTabIndex: false
  hideCloseButton: false
  cursorBlink: true
hotkeys:
  profile: {}
  shell: {}
  toggle-window:
    - - Ctrl-Shift-Space
  close-pane:
    - - Ctrl-Shift-W
  close-tab: []
  split-right:
    - - Ctrl-Shift-L
  previous-word: []
  next-word: []
  delete-previous-word:
    - - Ctrl-Backspace
  delete-next-word: []
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  home:
    - Home
  end:
    - End
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  ctrl-c:
    - Ctrl-C
  copy-current-path: []
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - Ctrl-Shift-N
  new-tab:
    - Ctrl-Shift-T
  profile-selector:
    - Ctrl-Shift-T
  toggle-fullscreen:
    - F11
  rename-tab:
    - Ctrl-Shift-R
  reopen-tab:
    - Ctrl-Shift-T
  toggle-last-tab: []
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-maximize:
    - Ctrl-Alt-Enter
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  switch-profile:
    - Ctrl-Alt-T
  profile-selectors: {}
  select-all:
    - Ctrl-Shift-A
serial: {}
ssh: {}
appearance:
  vibrancy: true
  opacity: 1
  frame: thin
  theme: Standard
  css: ''
  dock: 'off'
  tabsLocation: top
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - theme-hype
enableAutomaticUpdates: true
version: 3
profiles: []
configSync:
  parts: {}
profileDefaults: {}
